import {
  constants,
  closeSync,
  fsyncSync,
  lstatSync,
  openSync,
  realpathSync,
  renameSync,
} from "node:fs";
import { lstat, mkdir, open, realpath, unlink } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { join, resolve } from "node:path";
import { BoardError, requireBoard } from "./errors.js";

function missing(error: unknown): boolean {
  return !!error && typeof error === "object" && "code" in error && error.code === "ENOENT";
}

// This directory is owned by this store, not a general-purpose file API. Filenames
// are generated by the store, and checked again here as defense in depth.
export class BoardDisk {
  readonly directory: string;
  constructor(directory: string) {
    this.directory = resolve(directory);
  }

  private path(name: string): string {
    requireBoard(
      /^[a-f0-9]{64}(?:\.[a-f0-9-]{36}\.snapshot)?\.json$/.test(name),
      400,
      "Invalid board filename",
    );
    return join(this.directory, name);
  }

  async prepare(): Promise<void> {
    await mkdir(this.directory, { recursive: true, mode: 0o700 });
    const stat = await lstat(this.directory);
    requireBoard(
      stat.isDirectory() &&
        !stat.isSymbolicLink() &&
        stat.uid === process.getuid?.() &&
        (stat.mode & 0o777) === 0o700 &&
        (await realpath(this.directory)) === this.directory,
      500,
      "Board directory must be private (0700), owned, and not symlinked",
    );
  }

  private checkDirectory(): void {
    const stat = lstatSync(this.directory);
    requireBoard(
      stat.isDirectory() &&
        stat.uid === process.getuid?.() &&
        (stat.mode & 0o777) === 0o700 &&
        realpathSync(this.directory) === this.directory,
      500,
      "Unsafe board directory",
    );
  }

  async read(name: string, max: number): Promise<Buffer | null> {
    await this.prepare();
    let file;
    try {
      file = await open(
        this.path(name),
        constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK,
      );
    } catch (error) {
      if (missing(error)) return null;
      throw new BoardError(500, "Cannot safely open board data");
    }
    try {
      const stat = await file.stat();
      requireBoard(
        stat.isFile() &&
          stat.uid === process.getuid?.() &&
          (stat.mode & 0o077) === 0 &&
          stat.nlink === 1 &&
          stat.size > 0 &&
          stat.size <= max,
        500,
        "Unsafe or oversized board file",
      );
      const bytes = Buffer.alloc(stat.size + 1);
      let size = 0;
      while (size < bytes.length) {
        const result = await file.read(bytes, size, bytes.length - size, size);
        if (!result.bytesRead) break;
        size += result.bytesRead;
      }
      const after = await file.stat();
      requireBoard(
        size === stat.size &&
          after.size === stat.size &&
          after.mtimeMs === stat.mtimeMs &&
          after.ctimeMs === stat.ctimeMs,
        500,
        "Board file changed while reading",
      );
      return bytes.subarray(0, size);
    } finally {
      await file.close();
    }
  }

  async write(
    name: string,
    bytes: Buffer,
    authorize: () => void,
    immutable = false,
  ): Promise<void> {
    await this.prepare();
    authorize();
    const destination = this.path(name);
    const temporary = join(this.directory, `.board-${randomUUID()}.tmp`);
    const file = await open(
      temporary,
      constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | constants.O_NOFOLLOW,
      0o600,
    );
    try {
      await file.writeFile(bytes);
      await file.sync();
    } catch (error) {
      await file.close();
      await unlink(temporary).catch(() => undefined);
      throw error;
    }
    await file.close();
    try {
      this.checkDirectory();
      try {
        const existing = lstatSync(destination);
        requireBoard(!immutable, 409, "Immutable snapshot already exists");
        requireBoard(
          existing.isFile() &&
            existing.uid === process.getuid?.() &&
            (existing.mode & 0o077) === 0 &&
            existing.nlink === 1,
          500,
          "Unsafe board destination",
        );
      } catch (error) {
        if (!missing(error)) throw error;
      }
      const directory = openSync(
        this.directory,
        constants.O_RDONLY | constants.O_DIRECTORY | constants.O_NOFOLLOW,
      );
      try {
        // There is deliberately no await between this final authorization and
        // rename: revocation/expiry cannot interleave with the commit point.
        authorize();
        renameSync(temporary, destination);
        fsyncSync(directory);
      } finally {
        closeSync(directory);
      }
    } finally {
      await unlink(temporary).catch(() => undefined);
    }
  }

  async removeSnapshot(name: string): Promise<void> {
    this.checkDirectory();
    await unlink(this.path(name)).catch((error) => {
      if (!missing(error)) throw error;
    });
  }
}
